In [1]:
%pip install gensim

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import gensim
from gensim.models import word2vec,keyedvectors

In [3]:
import gensim.downloader as api
wv=api.load('word2vec-google-news-300')

vec_king=wv['king']

In [4]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [5]:
import pandas as pd
messages=pd.read_csv('..\SMSSpamCollection.txt',sep='\t',names=['label','message'])

<>:2: SyntaxWarning: invalid escape sequence '\S'
<>:2: SyntaxWarning: invalid escape sequence '\S'
C:\Users\UJJWAL\AppData\Local\Temp\ipykernel_5528\1042683367.py:2: SyntaxWarning: invalid escape sequence '\S'
  messages=pd.read_csv('..\SMSSpamCollection.txt',sep='\t',names=['label','message'])


In [7]:
from nltk.stem import WordNetLemmatizer
import re
lemmatizer=WordNetLemmatizer()

In [8]:
corpus=[]

for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review ]
    review=' '.join(review)
    corpus.append(review)

In [62]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus, messages['message']) if i<1]

[[0, '', '645'], [0, '', ':) '], [0, '', ':-) :-)']]

In [9]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [10]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [11]:
words=[]

for sent in corpus:
    sent_token=sent_tokenize(sent)

    for sent in sent_token:
        words.append(simple_preprocess(sent))


In [12]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [13]:
import gensim

In [16]:
## lets train word2vec from scratch
model=gensim.models.Word2Vec(words)

In [17]:
## To get all the vocabulary
model.wv.index_to_key

['to',
 'you',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'if',
 'will',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'day',
 'ok',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'she',
 'home',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'they',
 'later',
 'please',
 'any',
 'pls',
 'her',
 'ha',
 'did',
 'co',
 'msg',
 'been',
 'min',
 'an',
 'some',
 'dear',
 'night',
 'make',
 'who',
 'here',
 'message',
 'well',
 'say',
 'where',
 're',
 'thing',
 'much',
 'hope

In [18]:
model.corpus_count

5569

In [19]:
model.epochs

5

In [21]:
model.wv.similar_by_word('good')

[('all', 0.9988034963607788),
 ('day', 0.9987841248512268),
 ('morning', 0.9987289309501648),
 ('amp', 0.9987287521362305),
 ('my', 0.9987151026725769),
 ('great', 0.9986951351165771),
 ('well', 0.9986923933029175),
 ('dear', 0.9986637234687805),
 ('happy', 0.9986395239830017),
 ('boy', 0.9986265897750854)]

In [24]:
model.wv['good']

array([-3.01186889e-01,  3.99380505e-01,  8.89657438e-02,  1.57196969e-01,
        1.19834825e-01, -7.11925328e-01,  2.23602846e-01,  7.53099024e-01,
       -4.52026486e-01, -1.67770073e-01, -2.75492549e-01, -6.77275121e-01,
        8.55049118e-03,  7.53318444e-02,  3.32619697e-01, -2.47377962e-01,
        1.79127976e-01, -4.22721773e-01, -1.43777028e-01, -8.47414017e-01,
        3.43991905e-01,  2.86023915e-01,  1.52009934e-01, -2.91374117e-01,
       -1.92743212e-01,  1.82224531e-02, -5.11094868e-01, -3.68220389e-01,
       -4.04422313e-01,  7.73676019e-03,  3.91234785e-01, -7.95618370e-02,
        1.29491553e-01, -3.32238436e-01, -1.94499254e-01,  5.69272995e-01,
        1.08070020e-02, -2.34115690e-01, -1.15675636e-01, -5.38233280e-01,
        2.25910500e-01, -3.62465560e-01, -2.77270347e-01,  5.40787689e-02,
        3.68908137e-01,  1.50747700e-02, -2.87424207e-01, -1.03191562e-01,
        1.06852271e-01,  2.13115528e-01,  2.08938599e-01, -2.76996464e-01,
       -6.06203042e-02,  

In [25]:
model.wv['good'].shape

(100,)

In [46]:

def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)
    
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)
                #or [np.zeros(len(model.wv.index_to_key))], axis=0)

In [47]:
%pip install tqdm

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [48]:
from tqdm import tqdm

In [53]:
#apply for the entire sentences
import numpy as np
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))


100%|██████████| 5569/5569 [00:00<00:00, 8612.89it/s]


In [54]:
X

[array([-1.92416534e-01,  2.56991118e-01,  7.19643161e-02,  1.04663610e-01,
         7.89748654e-02, -5.03257632e-01,  1.50545090e-01,  4.98056918e-01,
        -3.00761372e-01, -1.23970456e-01, -1.90245062e-01, -4.42862630e-01,
        -2.96425838e-02,  5.17425016e-02,  2.33955324e-01, -1.66964978e-01,
         1.05898105e-01, -2.84576863e-01, -9.73191187e-02, -5.64455926e-01,
         2.04895243e-01,  1.82195380e-01,  8.97730291e-02, -1.98774904e-01,
        -1.37096718e-01,  1.22545278e-02, -3.72942626e-01, -2.51266181e-01,
        -2.73437113e-01,  1.01898210e-02,  2.65057653e-01, -4.27110717e-02,
         8.66128057e-02, -2.29620472e-01, -1.34976909e-01,  3.92024904e-01,
         2.31544990e-02, -1.63429663e-01, -1.04499415e-01, -3.63493860e-01,
         1.49814531e-01, -2.48424381e-01, -1.97615087e-01,  1.85836125e-02,
         2.72625655e-01, -8.78125720e-05, -1.90956846e-01, -5.90052195e-02,
         1.05290048e-01,  1.51622906e-01,  1.16211332e-01, -1.87417403e-01,
        -2.6

In [55]:
len(X)

5569

In [74]:
##Independent features
X_new = np.array(X, dtype=object)

In [75]:
messages.shape

(5572, 2)

In [76]:
X_new.shape

(5569,)

In [77]:
X_new[0].shape

(100,)

In [78]:
## Dependent Feature
#Output Feature
y = messages[list(map(lambda x: len(x)>0 ,corpus))]
y=y['label'].map({'ham': 0, 'spam': 1}).values

In [79]:
y.shape

(5569,)

In [80]:
X[0]

array([-1.92416534e-01,  2.56991118e-01,  7.19643161e-02,  1.04663610e-01,
        7.89748654e-02, -5.03257632e-01,  1.50545090e-01,  4.98056918e-01,
       -3.00761372e-01, -1.23970456e-01, -1.90245062e-01, -4.42862630e-01,
       -2.96425838e-02,  5.17425016e-02,  2.33955324e-01, -1.66964978e-01,
        1.05898105e-01, -2.84576863e-01, -9.73191187e-02, -5.64455926e-01,
        2.04895243e-01,  1.82195380e-01,  8.97730291e-02, -1.98774904e-01,
       -1.37096718e-01,  1.22545278e-02, -3.72942626e-01, -2.51266181e-01,
       -2.73437113e-01,  1.01898210e-02,  2.65057653e-01, -4.27110717e-02,
        8.66128057e-02, -2.29620472e-01, -1.34976909e-01,  3.92024904e-01,
        2.31544990e-02, -1.63429663e-01, -1.04499415e-01, -3.63493860e-01,
        1.49814531e-01, -2.48424381e-01, -1.97615087e-01,  1.85836125e-02,
        2.72625655e-01, -8.78125720e-05, -1.90956846e-01, -5.90052195e-02,
        1.05290048e-01,  1.51622906e-01,  1.16211332e-01, -1.87417403e-01,
       -2.64027044e-02,  

In [81]:

X[0].reshape(1,-1).shape

(1, 100)

In [87]:
## this is the final independent features
df = pd.concat([pd.DataFrame(x.reshape(1, -1)) for x in X], ignore_index=True)

C:\Users\UJJWAL\AppData\Local\Temp\ipykernel_5528\1889022550.py:2: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([pd.DataFrame(x.reshape(1, -1)) for x in X], ignore_index=True)


In [88]:
df.head

<bound method NDFrame.head of             0         1         2         3         4         5         6   \
0    -0.192417  0.256991  0.071964  0.104664  0.078975 -0.503258  0.150545   
1    -0.167261  0.223853  0.059055  0.095964  0.065390 -0.448806  0.121715   
2    -0.185589  0.266131  0.095003  0.137029  0.075967 -0.558213  0.161670   
3    -0.262804  0.350696  0.088817  0.141508  0.102935 -0.669498  0.197014   
4    -0.229322  0.295938  0.084961  0.119113  0.101890 -0.573712  0.164393   
...        ...       ...       ...       ...       ...       ...       ...   
5564 -0.222840  0.317406  0.109939  0.145830  0.094505 -0.632631  0.194733   
5565 -0.240835  0.303489  0.093310  0.138392  0.110805 -0.620090  0.177937   
5566 -0.262135  0.361263  0.090821  0.131879  0.099221 -0.668554  0.202514   
5567 -0.235602  0.316118  0.089668  0.128608  0.097347 -0.610067  0.177808   
5568 -0.263547  0.332663  0.092730  0.138559  0.109003 -0.652972  0.188154   

            7         8         9